[package]
name = "async-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.1", features = ["v4", "fast-rng"] }
clap = "3.2.25"
log = "0.4"
env_logger = "0.9"
rand = "0.8"
